#development:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: db/development.sqlite3


 development:
   adapter: mysql2
   database: my_library
   username: root
   password: 666
   host: localhost

